### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by roshan-koirala** [eqcorrscan/EQcorrscan#494]
# What do you need help with?
Sampling rate issue
# Provide an example so that we can reproduce your problem
end_Time = st[0].stats.endtime
start_Time = st[0].stats.starttime
process_len = end_Time - start_Time #60*60*24 # 60*60*24 

# bandpass 10-100 Hz, 5.0 second template + 1.0 s prepick = 6.0 second template
tribe = Tribe().construct(
    method="from_meta_file", meta_file=catalog, st=st.copy(), lowcut=10.0, highcut=100.0,
    samp_rate = 250, length=4.0, filt_order=4, prepick=0.5, swin='all',
    process_len=process_len, parallel=True)
# What help would you like?
My data stream is missing the last sample for the daylong data with a sampling rate of 250 Hz. When I try to construct tribe, it gives the following error. ValueError: Data sampling-rate * length (249.99998474121094 * 86400 = 21599998.681640625) does not match number of samples (21599999) for NE.BM01..EHE
# What is your setup? (please complete the following information):**
 - Operating System: Mac
 - Python version: 3.7
 - EQcorrscan version: latest

**Comment by roshan-koirala** [comment]
Hi, Thanks for the explanation and potential solutions. 

After I generated the catalog for a template, I was trying to generate the Tribe as below.

# build stream of all stations for detection from 'data' directory
date = 20170919
file_list = glob.glob(f"{wf_dir}/*/*_{date}.mseed")

# load files into stream
st = Stream()
for file in file_list:
    st += read(file)

end_Time = st[0].stats.endtime
start_Time = st[0].stats.starttime
# update process_len to the duration in seconds
process_len = end_Time - start_Time #60*60*24 # 60*60*24 

# bandpass 10-100 Hz, 5.0 second template + 1.0 s prepick = 6.0 second template
tribe = Tribe().construct(
    method="from_meta_file", meta_file=catalog, st=st.copy(), lowcut=10.0, highcut=100.0,
    samp_rate = 250, length=4.0, filt_order=4, prepick=0.5, swin='all',
    process_len=process_len, parallel=True, ignore_bad_data=True)

However, I got this error.

RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/roshan/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/roshan/opt/anaconda3/lib/python3.8/site-packages/eqcorrscan/utils/pre_processing.py", line 558, in process
    raise ValueError(msg)
ValueError: Data sampling-rate * length (249.99998474121094 * 86400 = 21599998.681640625) does not match number of samples (21599999) for NE.BM01..EHE
"""


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/var/folders/2q/7mrsf6t91h52hpsxx0j2j6rh0000gn/T/ipykernel_76939/2489019388.py", line 7, in <module>
    tribe = Tribe().construct(

  File "/Users/roshan/opt/anaconda3/lib/python3.8/site-packages/eqcorrscan/core/match_filter/tribe.py", line 1016, in construct
    templates, catalog, process_lengths = template_gen.template_gen(

  File "/Users/roshan/opt/anaconda3/lib/python3.8/site-packages/eqcorrscan/core/template_gen.py", line 352, in template_gen
    st = pre_processing.dayproc(

  File "/Users/roshan/opt/anaconda3/lib/python3.8/site-packages/eqcorrscan/utils/pre_processing.py", line 386, in dayproc
    stream_list = [p.get() for p in results]

  File "/Users/roshan/opt/anaconda3/lib/python3.8/site-packages/eqcorrscan/utils/pre_processing.py", line 386, in <listcomp>
    stream_list = [p.get() for p in results]

  File "/Users/roshan/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value

ValueError: Data sampling-rate * length (249.99998474121094 * 86400 = 21599998.681640625) does not match number of samples (21599999) for NE.BM01..EHE

**Comment by flixha** [comment]
Just before the traceback, did you get a log message on padding?

And can you try with `clip=True` as an additional parameter  to `Tribe().construct(`

And one small thing: if you put the following text around the code  in your post then it becomes nicely highlighted and easier to read (remove the ")
```
```python
text...
"```
```

**Comment by roshan-koirala** [comment]
Thanks.

No, I did not get any log message on padding.```clip=True``` does not change anything.

**Comment by flixha** [comment]
Ok, you should be able to get more info by setting the logger levels to info or debug, try this at the beginning of the script:

```python
import logging
Logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s\t%(name)s\t%(levelname)s\t%(message)s")
```

**Comment by roshan-koirala** [comment]
I got ```'2022-06-02 04:43:16,930	eqcorrscan.core.template_gen	INFO	Pre-processing data'``` prior to the ```RemoteTraceback:.......```

**Comment by roshan-koirala** [comment]
HI, resampling works.  ```stream.resample(250.0)``` Let's see how it goes. Thanks.

**Comment by calum-chamberlain** [comment]
Sorry for missing this while I was on leave - it looks like you have sorted this out, but it might be worth ensuring that your data are sampled as you expect them to be in general. A sampling rate of 249.99998474121094 is unusual. You probably want to check that the timing in your data are correct to avoid possible issues with aligning traces.

**Comment by roshan-koirala** [comment]
While creating the mseed file, the last sample was missing, so the odd frequency.

**Comment by calum-chamberlain** [comment]
Okay, so instead of the sampling-rate being wrong you should manually change the sampling-rate to the correct value. Resampling will result in incorrect data. **Please do not resample if you know that your trace.stats are wrong** - fix the stats rather than damaging the data.
Changing the sampling-rate should update the endtime and delta stats values to the correct values automatically.

**Comment by roshan-koirala** [comment]
Thanks, did that.

**Comment by flixha** [comment]
Just as a note if someone comes across this type of issue with other stations:
I have seen sampling rates like  249.99998474121094 for recording systems where the digitizer itself doesn't have a GPS connected; but where a computer that receives the data from the digitizer adds a GPS timestamp. In that case resampling / interpolating to the regular sampling rate is probably the best for EQcorrscan I think. If the difference is very small, like one sample or less for 24 hours of data, then it can be safe to just fix the trace stats - but it's not guaranteed depending on your problem.

I have seen these sampling rates for two GSN stations; BORG, and ESK including for recent years and not just older data.

**Comment by calum-chamberlain** [comment]
That is interesting @flixha - have you had a look at those data in any different programs, or been able to extract the headers? I'm curious about how the odd sampling-rate is being derived - is that sampling rate or the sample interval actually "wrong" in the mseed header, or was it actually recording at 250Hz and something went wrong reading the data? Definitely if the digitizer was sampling at that odd sampling frequency then resampling or interpolating is the correct approach. 

We can probably close this soon, but if anyone has any suggestions for changing the title of this issue to make it easier to find if someone runs into the same issue then go for it.

**Comment by flixha** [comment]
@calum-chamberlain Didn't want to capture the thread but here for some examples:
Here is an example with the headers of 3 data records from II.ESK, read with IRIS's `msi -p -vv`. 

So in this example it looks like the start time of each record is time stamped, but each time stamp contains some extra microseconds so that the actual sample rate differs a bit from the nominal one.
```
Read record length of 4096 bytes
II_ESK_00_BHZ, 000000, M
             start time: 2010,054,08:44:29.231000
      number of samples: 2810
     sample rate factor: 20  (20 samples per second)
 sample rate multiplier: 1
   number of blockettes: 2
        time correction: 0
            data offset: 128
 first blockette offset: 48
         BLOCKETTE 1000: (Data Only SEED)
              next blockette: 56
                    encoding: STEIM 1 Compression (val:10)
                  byte order: Big endian (val:1)
               record length: 4096 (val:12)
          BLOCKETTE 100: (Sample Rate)
              next blockette: 0
          actual sample rate: 19.99998474
Read record length of 4096 bytes
II_ESK_00_BHZ, 000000, M
             start time: 2010,054,08:46:49.731100
      number of samples: 2960
     sample rate factor: 20  (20 samples per second)
 sample rate multiplier: 1
   number of blockettes: 2
        time correction: 0
            data offset: 128
 first blockette offset: 48
         BLOCKETTE 1000: (Data Only SEED)
              next blockette: 56
                    encoding: STEIM 1 Compression (val:10)
                  byte order: Big endian (val:1)
               record length: 4096 (val:12)
          BLOCKETTE 100: (Sample Rate)
              next blockette: 0
          actual sample rate: 19.99998474
Read record length of 4096 bytes
II_ESK_00_BHZ, 000000, M
             start time: 2010,054,08:49:17.731300
      number of samples: 1088
     sample rate factor: 20  (20 samples per second)
 sample rate multiplier: 1
   number of blockettes: 2
        time correction: 0
            data offset: 128
 first blockette offset: 48
         BLOCKETTE 1000: (Data Only SEED)
              next blockette: 56
                    encoding: STEIM 1 Compression (val:10)
                  byte order: Big endian (val:1)
               record length: 4096 (val:12)
          BLOCKETTE 100: (Sample Rate)
              next blockette: 0
          actual sample rate: 19.99998474
```

Now I'm now expert at what recorders they used at the II-part of the GSN network, but it seems to be quite common there (4 out of 4 stations I have been using data from showed this behavior).

The explanation about adding GPS time stamps to the data after recording was something that occurred in our network NS for some older recording setups (so I'm not sure it's the same thing for II). Here the data was recorded in Seisan waveform format, and converted to mseed with wavetool. Then the headers look like this (no entry for actual sample rate; instead nominal sample rate different for some records):
```
NS_NSS_00_BHZ, 000048, D
             start time: 2009,018,19:02:46.545900
      number of samples: 2722
     sample rate factor: 3599  (49.98611111 samples per second)
 sample rate multiplier: -72
         activity flags: [00000000] 8 bits
    I/O and clock flags: [00000000] 8 bits
     data quality flags: [00000000] 8 bits
   number of blockettes: 1
        time correction: 0
            data offset: 64
 first blockette offset: 48
         BLOCKETTE 1000: (Data Only SEED)
              next blockette: 0
                    encoding: STEIM 1 Compression (val:10)
                  byte order: Little endian (val:0)
               record length: 4096 (val:12)
               reserved byte: 0
NS_NSS_00_BHZ, 000001, D
             start time: 2009,018,19:03:41.000000
      number of samples: 3772
     sample rate factor: 50  (50 samples per second)
 sample rate multiplier: 1
         activity flags: [00000000] 8 bits
    I/O and clock flags: [00000000] 8 bits
     data quality flags: [00000000] 8 bits
   number of blockettes: 1
        time correction: 0
            data offset: 64
 first blockette offset: 48
         BLOCKETTE 1000: (Data Only SEED)
              next blockette: 0
                    encoding: STEIM 1 Compression (val:10)
                  byte order: Little endian (val:0)
               record length: 4096 (val:12)
               reserved byte: 0
```
