### ISSUE TITLE
`concurrent_processing=True` in `Tribe.detect()` failed to work with `fmf` correlation backend when using cpu (`concurrency='multithread'`)

### ISSUE THREAD

**Issue by zhong-yy** [eqcorrscan/EQcorrscan#599]
**Describe the bug**
When using `fmf` as a cross-correlation backend in CPU  (`concurrency='multithread'`), the `concurrent_processing=True` option can make the code crashed. I haven't tested it on a  GPU with `concurrency='concurrent'`. The error doesn't happen when `concurrent_processing=False`.

**To Reproduce**
Steps to reproduce the behaviour (including error messages if applicable - if this gets really long, maybe make a gist?)
```python
party=tribe.client_detect(
           ...
           xcorr_func="fmf",
           concurrent_processing=True,
           concurrency="multithread"
)
```
Error message:
```
2024-12-14 16:07:32,430 | eqcorrscan.core.match_filter.tribe | ERROR | Caught exception in correlator: 
 'NoneType' object is not subscriptable                                                                                                                       
 File "eqcorrscan/core/match_filter/tribe.py", line 1172, in _detect_concurrent
     all_peaks, thresholds, no_chans, chans = _corr_and_peaks( 
 File "eqcorrscan/core/match_filter/helpers/tribe.py", line 407, in _corr_and_p$aks
    if len(cccsums[0]) == 0:
2024-12-14 16:07:32,522 | eqcorrscan.core.match_filter.tribe | INFO | Collecting party
2024-12-14 16:07:32,522 | eqcorrscan.core.match_filter.helpers.processes | ERROR | Poisoned
2024-12-14 16:07:32,522 | eqcorrscan.core.match_filter.tribe | ERROR | Killed
2024-12-14 16:07:32,523 | eqcorrscan.core.match_filter.tribe | ERROR | Raising error 'NoneType' object is not subscriptable in main process
2024-12-14 16:07:32,544 | eqcorrscan.core.match_filter.helpers.processes | INFO | _make_detections got None, stopping
2024-12-14 16:07:32,649 | eqcorrscan.core.match_filter.tribe | WARNING | Terminating downloader
2024-12-14 16:07:32,847 | eqcorrscan.core.match_filter.tribe | WARNING | Terminating prepper
2024-12-14 16:07:32,847 | eqcorrscan.core.match_filter.tribe | WARNING | Terminating detector
2024-12-14 16:07:32,847 | eqcorrscan.core.match_filter.tribe | INFO | Finished closing processes
2024-12-14 16:07:32,847 | eqcorrscan.core.match_filter.tribe | INFO | Emptying times
2024-12-14 16:07:32,847 | eqcorrscan.core.match_filter.tribe | INFO | Closing times
2024-12-14 16:07:32,847 | eqcorrscan.core.match_filter.tribe | INFO | Emptying poison
2024-12-14 16:07:32,847 | eqcorrscan.core.match_filter.tribe | INFO | Closing poison
2024-12-14 16:07:32,848 | eqcorrscan.core.match_filter.tribe | INFO | Emptying stream
2024-12-14 16:07:32,848 | eqcorrscan.core.match_filter.tribe | INFO | Closing stream
2024-12-14 16:07:32,848 | eqcorrscan.core.match_filter.tribe | INFO | Emptying prepped
2024-12-14 16:07:32,848 | eqcorrscan.core.match_filter.tribe | INFO | Closing prepped
2024-12-14 16:07:32,848 | eqcorrscan.core.match_filter.tribe | INFO | Emptying peaks
2024-12-14 16:07:32,848 | eqcorrscan.core.match_filter.tribe | INFO | Closing peaks
2024-12-14 16:07:32,848 | eqcorrscan.core.match_filter.tribe | INFO | Emptying party_file
2024-12-14 16:07:32,848 | eqcorrscan.core.match_filter.tribe | INFO | Closing party_file
2024-12-14 16:07:32,848 | eqcorrscan.core.match_filter.tribe | INFO | Finished closing queues
2024-12-14 16:07:32,848 | eqcorrscan.core.match_filter.tribe | INFO | Admin complete, raising error

Traceback (most recent call last):
  File "eqcorrscan/core/match_filter/tribe.py", line 1546, in client_detect
    party = self.detect(
  File "eqcorrscan/core/match_filter/tribe.py", line 901, in detect
    party = self._detect_concurrent(*args, **inner_kwargs)
  File "eqcorrscan/core/match_filter/tribe.py", line 1233, in _detect_concurrent
    self._on_error(internal_error)
  File "eqcorrscan/core/match_filter/tribe.py", line 1607, in _on_error
    raise error
TypeError: 'NoneType' object is not subscriptable
```

**Expected behavior**
`xcorr_func="fmf"` works with  `concurrent_processing=True` and `concurrency='multithread'`  without error.

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 24.04.1
 - Python version: 3.10
 - EQcorrscan version: 0.5.dev

**Additional context**
No

**Comment by calum-chamberlain** [comment]
This looks like an error stemming from FMF, not from EQcorrscan. I suggest you try and did out the error from FMF and work out what went wrong there.
